### ISSUE TITLE
MangaHere: Image access denied

### ISSUE THREAD

**Issue by ricemashi** [consumet/consumet.ts#111]
### Describe the bug

The api response from the image property doesnt work when the url is opened

### Steps to reproduce

1. Use the mangahere api route
2. Fetch data from the manga info url (eg: https://api.consumet.org/manga/mangahere/info?id={anime_id})
3. Get the `image` property
4. When used it will show undefined

### Expected behavior

It should render the given image in the url

### Actual behavior

It showed a page saying access denied:

![image](https://user-images.githubusercontent.com/116453651/202651792-21aefd90-29c8-44db-ba9c-8e00ba61e22f.png)

**Comment by ricemashi** [comment]
I am going to conclude this issue as I have resolved it myself, it was just a missing header issue since I did not include the `referer` header into my request.

**Comment by riimuru** [comment]
@ricemashi you can also use `https://api.consumet.org/utils/image-proxy?url=image_url&referer=image_referer_url`

**Comment by ricemashi** [comment]
Hey @riimuru, that proxy route actually removed the hassle of making my own proxy server (didn't know that existed in the consumet api). Your solution was really helpful there, thanks!
