### ISSUE TITLE
Crunchyroll mapping is inaccurate

### ISSUE THREAD

**Issue by K3NOXOFFICIAL** [consumet/consumet.ts#137]
### Describe the bug

When Selectig Provider other than GOGOanime it's Showing a Wrong Anime

### Steps to reproduce

For example, if I want to watch Beast Tamer and select a different provider than gogoanime, it shows a completely different anime.

Here it works with Gogoanime (Its 24m in lenght)
![image](https://user-images.githubusercontent.com/46091052/207126799-ed2f7db2-57c9-456e-bc06-db10bdad9372.png)

Here it doesn't work with Crunchyroll (Its 4m in lenght)
![image](https://user-images.githubusercontent.com/46091052/207127059-4a6f6d54-8d2b-4183-9475-c0dfd39231a7.png)

### Expected behavior

Should show the right anime.

### Actual behavior

Shows a completely different Anime.

### Additional context

Happened with quite a few animes but its not limited to Crunchyroll only, happened with Animefox too.

**Comment by ErrorErrorError** [comment]
Does this only happen with sub, dub or both? I can't seem to be able to reproduce this issue on my end.

**Comment by K3NOXOFFICIAL** [comment]
@ErrorErrorError Happens With both, tho Dub isn't really working for Crunchyroll and AnimeFox atm tbh.
Tho ***riimuru*** was able to Reproduce it.

**Comment by ErrorErrorError** [comment]
Which endpoint are you using to retrieve the information? I do see that using `fetchAnimeInfo` does not return the correct episodes for crunchy roll as of now, and might be the cause for the other providers too.

**Comment by K3NOXOFFICIAL** [comment]
@ErrorErrorError 

I'm not really sure what exactly you mean.
But I'm using it on [Ahsanime](https://github.com/Ashanime/Ashanime-Web-App), here are the [configs for the project](https://github.com/Ashanime/Ashanime-Web-App/tree/KENOX/src/backend).
[Here's The website](https://ashanime.pro) if you need it for testing or smth.

If you need smth else pls describe further so I understand.

**Comment by ErrorErrorError** [comment]
As of now, there doesn't seem to be a fix to correctly map AND return the correct episodes using Crunchyroll. 

I will see if I can fix the issue with other providers.

**Comment by K3NOXOFFICIAL** [comment]
@ErrorErrorError Thanks a lot.
