### ISSUE TITLE
Mangareader

### ISSUE THREAD

**Issue by August4599** [consumet/consumet.ts#16]
### Source name

Mangareader

### Source link

https://mangareader.to

### Language

English

### Source type

Manga

**Comment by Eltik** [comment]
If I may MangaReader has a custom image reverser. You have to run the function on the website itself. It's a huge pain and might require Puppeteer to do this. But it is a good site.

**Comment by TDanks2000** [comment]
> 

this was not necessary they had a ajax image api

**Comment by Eltik** [comment]
> > If I may MangaReader has a custom image reverser. You have to run the function on the website itself. It's a huge pain and might require Puppeteer to do this. But it is a good site.
> 
> this was not necessary they had a ajax image api


Ah thanks I did not notice that.
