### ISSUE TITLE
zoro.to fetchEpisodeSources error

### ISSUE THREAD

**Issue by ThaUnknown** [consumet/consumet.ts#194]
### Describe the bug

The zoro.to provider doesn't handle an edge case where the sub server is actually called RAW

### Steps to reproduce

// https://zoro.to/watch/a-day-before-us-season-zero-3782?ep=85392
// https://zoro.to/watch/aoharu-x-machinegun-2739
```js
const zoro = new ANIME.Zoro()
const info = await zoro.fetchAnimeInfo(id)
for (const episode of info.episodes) {
   const data = await zoro.fetchEpisodeSources(episode.id) // will error
}
```

### Expected behavior

fetchEpisodeSources to handle getting servers correctly

### Actual behavior

fetchEpisodeSources fails on servers named RAW, or when server doesn't hjave sub, only DUB

### Additional context

issue is caused by retrieveServerId, as it blindly assumes sub|dub rather than checking possible values

**Comment by aldairandre** [comment]
friend, I believe that if you change the fourth line of your script to 
```
 let data = await zoro.fetchEpisodeSources(episode.id) 
```
you will get the data from method fetchEpisodeSources

new code 
```
const zoro = new ANIME.Zoro()
const info = await zoro.fetchAnimeInfo(id)
for (const episode of info.episodes) {
  let data = await zoro.fetchEpisodeSources(episode.id) 
}
```

you can also create an array to save all the data

**Comment by Thor4201** [comment]
I have a similar kind of issue with the latest consumet, eg "Sao" displays subbed/dubbed full info as far as I could see, vermeil in gold episode 1 is the only 1 that lists any dubs/subs info, episode 2 lists 1 sub I've reverted back to my old consumet folder for local host and it's resolved that issue with zoro. Although I don't see anything that could be conflicting with it myself but I'm not too knowledgeable in this area. I'll continue messing around with it.
