### ISSUE TITLE
I would like to create an anime website but I don't know how to get the api

### ISSUE THREAD

**Issue by K4rnaSieg** [consumet/consumet.ts#238]
### Source name

animania

### Source link

animania.com/animes

### Language

inglês

### Source type

Anime

### Additional info

I was wanting to create an anime website but I'm having difficulties, I'm not able to put the anime on the website, so I'm looking for an api

**Comment by TDanks2000** [comment]
join the [discord](https://discord.gg/consumet) and we can help you out there
