### ISSUE TITLE
PT-BR SubAnimes Provider

### ISSUE THREAD

**Issue by DaniHRE** [consumet/consumet.ts#296]
### Source name

SubAnimes

### Source link

https://subanimes.org/

### Language

Portuguese(Brazil)

### Source type

Anime

### Additional info

Anime subbed in PT-BR

**Comment by aldairandre** [comment]
Descorde que esse seja um bom provedor de anime com legendas em PT-BR, ate pensei em criar um provedor com esse site e enviar um PR, mas ele é bem limitado!

**Comment by DaniHRE** [comment]
Peça por outros sites então, os sites bons de anime PT-BR estão sendo barrados, e muitos links streaming caindo.
Seja por DMCA ou piores.

**Comment by aldairandre** [comment]
Irmão, eu acredito que o provedor da zoro.to atende bem as necessidades para quem deseja assistir os seus animes e ter as legendas em PT-BR, vc ja tentou acessa o site zoro.to, tenta ai e depois diz pra mim se vc ainda preferem que add um novo provedor de anime!
O que eu estou aqui pensando é que seria bom se vc tivesse uns sites bons para manga com legendas em PT-BR, isso sim eu acredito que seria bom para se add ao consume.ts.

**Comment by DaniHRE** [comment]
Acabei verificando isso agora, não havia visto que o Zoro provia dublagem em PT-BR, agora que vi isso, acho que posso construir algo encima disso, muito obrigado pela indicação @aldairandre , agradeço a resposta.
