### ISSUE TITLE
[Flixhq] fetchEpisodeSources with Vidcound extractors throw Malformed UTF-8 data error

### ISSUE THREAD

**Issue by pepelele** [consumet/consumet.ts#297]
### Describe the bug

fetchEpisodeSources with Vidcound extractors throw Malformed UTF-8 data

### Steps to reproduce

run yarn test:movies

### Expected behavior

Return the movie sources

### Actual behavior

hrow Malformed UTF-8 data error

### Additional context

![332960343_1874773336225378_4415681396784268907_n](https://user-images.githubusercontent.com/84853682/223737403-f2c825b3-a014-4a56-aa7c-b6caca831dd6.png)

**Comment by 3IMAD69** [comment]
this https://github.com/consumet/consumet.ts/blob/e487e39fc946f7537168df7f1062f6e51f68e26c/src/extractors/vidcloud.ts#LL48C2-L48C2 reutrns an invalid/old key hope they fixed soon

**Comment by 3IMAD69** [comment]
nvm now its workin , it's been updated

**Comment by pepelele** [comment]
Is there any way to get the key 🤔 ?... from the time the key is expired to the time the key is updated about 4 hours... that's too long

**Comment by Eltik** [comment]
Looks like there's an issue with Vizcloud. We'll get a fix soon.

**Comment by enimax-anime** [comment]
> Is there any way to get the key 🤔 ?... from the time the key is expired to the time the key is updated about 4 hours... that's too long

The key is updated every hour. My program, which Consumet uses, checks for a new key every 10 seconds. For some reason,bmy program broke and I just had to restart it.

**Comment by Eltik** [comment]
Also I think this works now? I could be wrong.

**Comment by pepelele** [comment]
yes seems like it's work normal now (y)
