### ISSUE TITLE
ZORO ISSUE

### ISSUE THREAD

**Issue by AuraMoon55** [consumet/consumet.ts#340]
### Describe the bug

Zoro changed the url 

### Steps to reproduce

Please change the url from zoro.to to sanji.to

### Expected behavior

All the features are working except fetchEpisodeSources

### Actual behavior

Changing Url helps

**Comment by Thor4201** [comment]
- zoro team member.:
We are currently using sanji.to to split load the traffic....it's temporary

**Comment by Thor4201** [comment]
If you're local hosting the consumet api, I suggest backing up your api local host folders when you update, then you can just start the host off your backup, the recent consumet update is the reason behind the zoro bug issue I believe. It retrieves certain episodes eg sword art online  works fine from what I see, one it doesn't "vermeil in gold" ep 2 onwards nothing from zoro. Gogoanime is working if that'll work for you for now tho till they sort the issue
