### ISSUE TITLE
CORS Origin Blocking in FlixHQ Provider

### ISSUE THREAD

**Issue by snoofox** [consumet/consumet.ts#347]
### Describe the bug

Unable to fetch data from FlixHQ

### Steps to reproduce

1. Instantiate a new FlixHQ object by calling the FlixHQ() constructor and assigning it to the flixhq variable.

`const flixhq = new MOVIES.FlixHQ();`

2. Call the fetchRecentMovies() or any other method on the flixhq object.

`const movies = await flixhq.fetchRecentMovies();`

it'll produce the error:
Access to XMLHttpRequest at 'https://flixhq.to/home' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Expected behavior

The expected behavior is that the flixhq.fetchRecentMovies() method successfully fetches the recent movies from the API server and returns a list of movies. The movies variable should contain the retrieved movie data, allowing further processing or display of the movie information

### Actual behavior

The actual behavior is that when executing the provided code snippet, the request made by flixhq.fetchRecentMovies() is blocked by the browser due to CORS origin restrictions. As a result, the browser throws a CORS error and prevents the request from reaching the API server.

### Additional context

To resolve the CORS origin blocking issue, one potential solution is to utilize a CORS proxy server like cors-anywhere. The cors-anywhere server acts as a middleware that adds the necessary CORS headers to API responses, bypassing the CORS restrictions enforced by the browser.

**Comment by Shichiha** [comment]
CORS blocking also happens in gogo's `fetchAnimeInfo`
