### ISSUE TITLE
Please add genres (gogoanime)

### ISSUE THREAD

**Issue by ghost** [consumet/consumet.ts#36]
It would be nice for genres to be added soon to consumet. I especially want to see gogoanime have genres added first.

**Comment by ahmedalashhab** [comment]
I think this issue may be closed as the feature exists via the anilist route?

**Comment by riimuru** [comment]
@ahmedalashhab the gogoanime genres is was different than the anilist one in terms of sorting.

**Comment by wearrrrr** [comment]
Necroposting here, but I added a version of it for the consumet api, on a private deployment, so hopefully it is a matter of time before the code is merged into consumet.ts. cheers!
