### ISSUE TITLE
FlixHQ and MovieHdWatch unable to run "fetchEpisodeSources"

### ISSUE THREAD

**Issue by forsyth47** [consumet/consumet.ts#372]
### Describe the bug

Both FlixHQ and MovieHdWatch is unable get links. The function fetchEpisodeSources gives out a error.

### Steps to reproduce

The code
```
import { MOVIES } from "@consumet/extensions"

const flixhq = new MOVIES.FlixHQ();

flixhq.fetchEpisodeSources('1167571', 'tv/watch-vincenzo-67955', 'doodstream').then(data => {
  console.log(data);
})
```

```
import { MOVIES } from "@consumet/extensions"

const mhw = new MOVIES.MovieHdWatch();

mhw.fetchEpisodeSources('16076', 'movie/watch-the-batman-online-16076').then(data => {
  console.log(data);
})
```

### Expected behavior

According to the docs;
The JSON output should be given.

[DOCS LINK](https://github.com/consumet/consumet.ts/blob/master/docs/providers/moviehdwatch.md#fetchepisodesources)

### Actual behavior

Its giving the below output. Same for both provider

```
/home/runner/comsumetts/node_modules/@consumet/extensions/dist/providers/movies/flixhq.js:185
                throw new Error(err.message);
                      ^

Error: Request failed with status code 403
    at FlixHQ.fetchEpisodeSources (/home/runner/comsumetts/node_modules/@consumet/extensions/dist/providers/movies/flixhq.js:185:23)

Node.js v18.12.1
```

### Additional context

I've even tried adding server, but didn't work.
I tried the REST API (self-hosted, since the [official one](https://api.consumet.org/movies/flixhq/) redirects to 9anime for some reason.) That didn't work either.
The API provides this > [self-hosted](https://conmet.vercel.app/movies/flixhq/watch?episodeId=86052&mediaId=movie/watch-fall-86052) and says "Something went wrong. Please try again later."

That is all the info I remember as for now. I'll be happy to provide anyother required info.
It seems someone has opened an issue in the REST-API repo, but their has been no response. [issue.](https://github.com/consumet/api.consumet.org/issues/477)

**Comment by forsyth47** [comment]
wow.

**Comment by riimuru** [comment]
@forsyth47 Flixhq has been working for a while now anyways.
