### ISSUE TITLE
2Embed.to

### ISSUE THREAD

**Issue by SlideMovies** [consumet/consumet.ts#39]
### Source name

2Embed

### Source link

https://www.2embed.to/

### Language

English

### Source type

Movie/TV

### Additional info

2Embed.to also uses rabbitstream (like FlixHQ), but it supports TMDb/IMDb IDs which are very helpful.

**Comment by SuperMechaDeathChrist** [comment]
You could totally build something amazing if you combine it with the cinemagoer python package, which does a pretty fast database look up of content available in imdb.

https://github.com/cinemagoer/cinemagoer

**Comment by SlideMovies** [comment]
ACE shutdown 2embed, so this can be closed.
