### ISSUE TITLE
Anilist Info Endpoint very slow

### ISSUE THREAD

**Issue by RazeViana** [consumet/consumet.ts#409]
### Describe the bug

When using the https://api.consumet.org/meta/anilist/info/{id}?provider={provider} endpoint, it seems to be insanely slow (34 secs average load time). Using the other Anilist endpoints are perfectly fine except for the info one. This is also is the same when self hosted

### Steps to reproduce

Attempt to fetch from: https://api.consumet.org/meta/anilist/info/21220

### Expected behavior

It should load faster, similar to the other routes.

### Actual behavior

![image](https://github.com/consumet/consumet.ts/assets/57551859/23529694-0c25-467d-9bd4-1f2d58218bb9)

It takes more that 30 secs to load Anime Info

### Additional context

I have also tried self-hosting consumet and the same behaviour occurs.

**Comment by vmxt** [comment]
To avoid traffic requests on the default API, as indicated in the consumet docs, you should provide your own `self-hosting`.

you can fork the consumet api and deploy it to `vercel` or `railway`.

**Comment by vmxt** [comment]
update #2 and no it's not a `bug`

**Comment by vmxt** [comment]
and no. this is not a bug. works well on my end

**Comment by vmxt** [comment]
To avoid traffic requests on the default API, as indicated in the consumet docs, you should provide your own `self-hosting` on the api.

you can fork the consumet api and deploy it to `vercel` or `railway`.

and no this is not a `bug`. works well on my end though.

**Comment by riimuru** [comment]
@RazeViana as @vmxt indicated, please self-host the API, and make sure to update the dependencies.
