### ISSUE TITLE
Flixhq not working

### ISSUE THREAD

**Issue by OshekharO** [consumet/consumet.ts#416]
### Describe the bug

This provider is no longer working 

### Steps to reproduce

Open https://api.consumet.org/movies/flixhq/{query}?page={number}
Type query
See the error

### Expected behavior

Should have shown the search response. Also it's redirecting me to https://proxy.anistreme.live/flixhq

### Actual behavior

{"ClassName":"System.InvalidOperationException","Message":"Only forwarded addresses starting with 'http://' or 'https://' are supported for HTTP requests.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at AspNetCore.Proxy.HttpExtensions.ExecuteHttpProxyOperationAsync(HttpContext context, HttpProxy httpProxy)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"AspNetCore.Proxy","WatsonBuckets":null}

**Comment by OshekharO** [comment]
Also api have not been updated?

Because even in Zoro I am getting this error.

{"message":{"message":"Request failed with status code 404","name":"AxiosError","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.27.2"},"method":"get","url":"https://github.com/enimax-anime/key/blob/e6/key.txt"},"code":"ERR_BAD_REQUEST","status":404}}

In https://api.consumet.org/anime/zoro/watch?episodeId=spy-x-family-17977$episode$89506$both&server=vidcloud

**Comment by riimuru** [comment]
@OshekharO if you’re self hosting run npm update or yarn upgrade

**Comment by OshekharO** [comment]
> @OshekharO if you’re self hosting run npm update or yarn upgrade. You need to self-host the api for flixhq to work

Okk thanks and what about zoro?

**Comment by riimuru** [comment]
@OshekharO Both viewasian and zoro should be working now as we changed the keys as of #412
