### ISSUE TITLE
FlixHQ Video Source

### ISSUE THREAD

**Issue by Cimasearch** [consumet/consumet.ts#419]
### Describe the bug

The video source stopped working again after 3 days fix.

### Steps to reproduce

Everything is working fine but video source.

### Expected behavior

Should get video playing

### Actual behavior

Getting error message: 
{"message":"Something went wrong. Please try again later."}

**Comment by riimuru** [comment]
use this (I just tested it and it works!)
```
/movies/flixhq/watch?episodeId=98446&mediaId=movie/watch-oppenheimer-98446&server=vidcloud
``` 
Make sure to use the `vidcloud` server.
