### ISSUE TITLE
One-piece anime info details are not coming 

### ISSUE THREAD

**Issue by Abhinavkuamr** [consumet/consumet.ts#420]
### Describe the bug

One-piece anime info details are not coming that im getting from Anilist, it is giving 500 error

### Steps to reproduce

Here i have hosted consumet , and when i try to get details of One piece anime whose ID is 21, it gives 500 error
https://aniplix-scraper.vercel.app/meta/anilist/info/21

### Expected behavior

it should give a complete json format with all details
like with anyother anime 
for example
https://aniplix-scraper.vercel.app/meta/anilist/info/22

### Actual behavior

it gave 500 error code instead of giving the full anime details

**Comment by vmxt** [comment]
I thought I was the only one who encounter this but `+1` to this issue

**Comment by riimuru** [comment]
@Abhinavkuamr @vmxt I just tested the api locally, and everything seems to work fine. Make sure to run to stay up to date with the consumet.ts code.
```
yarn upgrade //or npm update
```

**Comment by vmxt** [comment]
@riimuru yea, looks good in the local works fine but in deployed URL it looks like I got `500` status
