### ISSUE TITLE
Cors origin policy

### ISSUE THREAD

**Issue by adiyat-shihab** [consumet/consumet.ts#421]
### Describe the bug

when i use the getcomic api i was blocked by cors origin policy 

### Steps to reproduce

Access to XMLHttpRequest at 'https://getcomics.info//page/1/?s=Batman' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Expected behavior

..

### Actual behavior

Access to XMLHttpRequest at 'https://getcomics.info//page/1/?s=Batman' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Additional context

Why not you create an read comic online api ?

**Comment by riimuru** [comment]
@adiyat-shihab Please refer to [CORS and M3U8 Proxies](https://discord.gg/JKkQMZSX) Post on discord help channel for possible fixes.
