### ISSUE TITLE
[Provider Request] Monoschinos (Spanish)

### ISSUE THREAD

**Issue by Berni04** [consumet/consumet.ts#438]
### Source name

Monoschinos

### Source link

https://monoschinos2.com/

### Language

Spanish

### Source type

Anime

### Additional info

Highly used and High quality site for Anime subbed to Spanish: 

I've found this page that gives a bit of idea of how it could be done, but I know nothing about TypeScript so I don't know if it is really useful or not: https://jimov-api-docs.vercel.app/api/monoschinos/getinfo

Also loots of people from LATAM and Spain watch anime and they mostly don't know enough English to use English subtitles.

**Comment by aleganza** [comment]
working on it
