### ISSUE TITLE
The latest version of @consumet/extensions (version 1.5.5) is not yet released on npm

### ISSUE THREAD

**Issue by Sodiumchloridy** [consumet/consumet.ts#459]
### Describe the bug

The latest version of @consumet/extensions on npm is still in version 1.5.4. but on Github it is version 1.5.5 for some time already. Certain fixes such as the gogoanime baseUrl changes for a few functions were not updated by usual means.

### Steps to reproduce

Running `npm install @consumet/extensions` and checking on the npm website shows that the latest version of @consumet/extensions is 1.5.4: https://www.npmjs.com/package/@consumet/extensions?activeTab=versions

Could only solve it by updating npm package via the Github repo directly:  `npm install github:consumet/consumet.ts`

### Expected behavior

Updates to version 1.5.5

### Actual behavior

Uses version 1.5.4 instead of version 1.5.5

### Additional context

I am no expert in CI or anything so please correct me if there is a misunderstanding but I would like to raise this up since it has caused some issues for me and a few others.

Hopefully I am in the right section.

**Comment by shubham7101** [comment]
You can you it like this
 "@consumet/extensions": "github:consumet/consumet.ts"
In package.json

reference
https://github.com/consumet/api.consumet.org/blob/main/package.json#L26

**Comment by Sodiumchloridy** [comment]
I see, alright, thanks a lot for providing a quick fix.
