### ISSUE TITLE
Add country route to flixHQ provider

### ISSUE THREAD

**Issue by dhelbegor** [consumet/consumet.ts#467]
**Is your feature request related to a problem? Please describe.**
I would like to have the country route option to get movies and tv series by country.

**Describe the solution you'd like**
add the scraper for the route country so when the person type /?country=KR
This route should bring movies and tv series filtered by that country.

**Comment by fsmdeveloper** [comment]
https://github.com/shin202/flixhq-core

Check this package. 

**[home](https://github.com/shin202/flixhq-core#home)
[fetchGenresList](https://github.com/shin202/flixhq-core#fetchgenresList)
[fetchCountriesList](https://github.com/shin202/flixhq-core#fetchcountriesList)
[fetchMovieByCountryOrGenre](https://github.com/shin202/flixhq-core#fetchmoviebycountryorgenre)
[fetchMovieByType](https://github.com/shin202/flixhq-core#fetchmoviebytype)
[fetchMovieByTopIMDB](https://github.com/shin202/flixhq-core#fetchmoviebytopimdb)
[fetchMovieInfo](https://github.com/shin202/flixhq-core#fetchmovieinfo)
[fetchEpisodeServers](https://github.com/shin202/flixhq-core#fetchepisodeservers)
[fetchEpisodeSources](https://github.com/shin202/flixhq-core#fetchepisodesources)
[search](https://github.com/shin202/flixhq-core#search)
[fetchFiltersList](https://github.com/shin202/flixhq-core#fetchfilterslist)
[filter](https://github.com/shin202/flixhq-core#filter)**

**Comment by riimuru** [comment]
@fsmdeveloper that package uses consumet's code so there's no point in using it

**Comment by fsmdeveloper** [comment]
> dhelbegor

Yes, Please make one with consumet.
