### ISSUE TITLE
flixhq api down, rabbitstream keys seem to have expired

### ISSUE THREAD

**Issue by ks3rr** [consumet/consumet.ts#470]
### Describe the bug

Hello, it appears that the e4 rabbitstream keys have expired, and the consumet API for FlixHQ is not functioning. Please check. Thank you.

### Steps to reproduce

FlixHq api hit returning failure.

### Expected behavior

should return list of sources

### Actual behavior

returning try again error

**Comment by fsmdeveloper** [comment]
I am also experiencing it. Someone told me that the issue is caused by https://keys4.fun/ being down.

**Comment by ClayArsenio26** [comment]
please update too the repo consumet.org :)

**Comment by fsmdeveloper** [comment]
Although https://keys4.fun/ is up and running, it still has the same issue. Could someone please fix it?

**Comment by stillmanpeeer** [comment]
solution: https://github.com/stillmanpeeer/rabbitstream

**Comment by dhelbegor** [comment]
> solution: https://github.com/stillmanpeeer/rabbitstream

It supports a high demand of requests per day?

**Comment by stillmanpeeer** [comment]
of course, i can give you 3-day trial

**Comment by dhelbegor** [comment]
> of course, i can give you 3-day trial

Nah. I don't pay for piracy. Thank u.

**Comment by fsmdeveloper** [comment]
> > of course, i can give you 3-day trial
> 
> Nah. I don't pay for piracy. Thank u.

Brother, you can this fork **https://github.com/Tommy0412/vidsrc-api**

It's working and free. example endpoint => **`https://vidsrc-api.onrender.com/76600`**

**Comment by stillmanpeeer** [comment]
> > > > of course, i can give you 3-day trial
> > > 
> > > 
> > > Nah. I don't pay for piracy. Thank u.
> > 
> > 
> > Brother, you can this fork **https://github.com/Tommy0412/vidsrc-api**
> > It's working and free. example endpoint => **`https://vidsrc-api.onrender.com/76600`**
> 
> That's what I'm talking about. the community united against piracy monetization.
> 
> we have this one too. that seems to be working just fine. he only extracts the source. So u need to use it along with consumet.
> 
> https://github.com/cool-dev-guy/rabbitthunder
> 
> This is the related conversation on consumet disc: https://discord.com/channels/987492554486452315/1219195838190977025/1219195838190977025
> 
> I haven't used this yet. but who is using says that is working just fine.

puppeteer they will block it soon trust me

**Comment by fsmdeveloper** [comment]
> > > > > of course, i can give you 3-day trial
> > > > 
> > > > 
> > > > Nah. I don't pay for piracy. Thank u.
> > > 
> > > 
> > > Brother, you can this fork **https://github.com/Tommy0412/vidsrc-api**
> > > It's working and free. example endpoint => **`https://vidsrc-api.onrender.com/76600`**
> > 
> > 
> > That's what I'm talking about. the community united against piracy monetization.
> > we have this one too. that seems to be working just fine. he only extracts the source. So u need to use it along with consumet.
> > https://github.com/cool-dev-guy/rabbitthunder
> > This is the related conversation on consumet disc: https://discord.com/channels/987492554486452315/1219195838190977025/1219195838190977025
> > I haven't used this yet. but who is using says that is working just fine.
> 
> puppeteer they will block it soon trust me

You are just thinking about your profit. leave this open-source community. you're greedy.

**Comment by fsmdeveloper** [comment]
> > > > of course, i can give you 3-day trial
> > > 
> > > 
> > > Nah. I don't pay for piracy. Thank u.
> > 
> > 
> > Brother, you can this fork **https://github.com/Tommy0412/vidsrc-api**
> > It's working and free. example endpoint => **`https://vidsrc-api.onrender.com/76600`**
> 
> That's what I'm talking about. the community united against piracy monetization.
> 
> we have this one too. that seems to be working just fine. he only extracts the source. So u need to use it along with consumet.
> 
> https://github.com/cool-dev-guy/rabbitthunder
> 
> This is the related conversation on consumet disc: https://discord.com/channels/987492554486452315/1219195838190977025/1219195838190977025
> 
> I haven't used this yet. but who is using says that is working just fine.

There are plenty of open-source scrapers available, based on Python, JavaScript, Go, Rust, etc. We don't need to pay for pirated content.

**Comment by stillmanpeeer** [comment]
Yes, I just want to advertise to those who need to use it, I also need to have costs to maintain the service and operation of my team, thank you.

**Comment by stillmanpeeer** [comment]
> > > > > of course, i can give you 3-day trial
> > > > 
> > > > 
> > > > Nah. I don't pay for piracy. Thank u.
> > > 
> > > 
> > > Brother, you can this fork **https://github.com/Tommy0412/vidsrc-api**
> > > It's working and free. example endpoint => **`https://vidsrc-api.onrender.com/76600`**
> > 
> > 
> > That's what I'm talking about. the community united against piracy monetization.
> > we have this one too. that seems to be working just fine. he only extracts the source. So u need to use it along with consumet.
> > https://github.com/cool-dev-guy/rabbitthunder
> > This is the related conversation on consumet disc: https://discord.com/channels/987492554486452315/1219195838190977025/1219195838190977025
> > I haven't used this yet. but who is using says that is working just fine.
> 
> [dhelbegor](https://github.com/dhelbegor) There are plenty of open-source scrapers available, based on Python, JavaScript, Go, Rust, etc. We don't need to pay for pirated content.

Do you think you're doing the right thing? You must understand that your actions damage the providers and people who use your code take advantage of it to make money for themselves, which is why the providers have to find a way to stop it.

**Comment by fsmdeveloper** [comment]
> > > > > > of course, i can give you 3-day trial
> > > > > 
> > > > > 
> > > > > Nah. I don't pay for piracy. Thank u.
> > > > 
> > > > 
> > > > Brother, you can this fork **https://github.com/Tommy0412/vidsrc-api**
> > > > It's working and free. example endpoint => **`https://vidsrc-api.onrender.com/76600`**
> > > 
> > > 
> > > That's what I'm talking about. the community united against piracy monetization.
> > > we have this one too. that seems to be working just fine. he only extracts the source. So u need to use it along with consumet.
> > > https://github.com/cool-dev-guy/rabbitthunder
> > > This is the related conversation on consumet disc: https://discord.com/channels/987492554486452315/1219195838190977025/1219195838190977025
> > > I haven't used this yet. but who is using says that is working just fine.
> > 
> > 
> > [dhelbegor](https://github.com/dhelbegor) There are plenty of open-source scrapers available, based on Python, JavaScript, Go, Rust, etc. We don't need to pay for pirated content.
> 
> Do you think you're doing the right thing? You must understand that your actions damage the provider. people who use your code take advantage of it to make money for themselves, which is why the providers have to find a way to stop it.

[stillmanpeeer](https://github.com/stillmanpeeer) How ironic! So you are from the providers? Don't you use a scraper for your application? We host the API/Application on our VPS. We will pay for our VPS, not for your API.

**Comment by stillmanpeeer** [comment]
> > > > > > of course, i can give you 3-day trial
> > > > > 
> > > > > 
> > > > > Nah. I don't pay for piracy. Thank u.
> > > > 
> > > > 
> > > > Brother, you can this fork **https://github.com/Tommy0412/vidsrc-api**
> > > > It's working and free. example endpoint => **`https://vidsrc-api.onrender.com/76600`**
> > > 
> > > 
> > > That's what I'm talking about. the community united against piracy monetization.
> > > we have this one too. that seems to be working just fine. he only extracts the source. So u need to use it along with consumet.
> > > https://github.com/cool-dev-guy/rabbitthunder
> > > This is the related conversation on consumet disc: https://discord.com/channels/987492554486452315/1219195838190977025/1219195838190977025
> > > I haven't used this yet. but who is using says that is working just fine.
> > 
> > 
> > [dhelbegor](https://github.com/dhelbegor) There are plenty of open-source scrapers available, based on Python, JavaScript, Go, Rust, etc. We don't need to pay for pirated content.
> 
> Do you think you're doing the right thing? You must understand that your actions damage the provider. people who use your code take advantage of it to make money for themselves, which is why the providers have to find a way to stop it.

No problem, do your job.

**Comment by Dragon-Batch** [comment]
> > > > > > > of course, i can give you 3-day trial
> > > > > > 
> > > > > > 
> > > > > > Nah. I don't pay for piracy. Thank u.
> > > > > 
> > > > > 
> > > > > Brother, you can this fork **https://github.com/Tommy0412/vidsrc-api**
> > > > > It's working and free. example endpoint => **`https://vidsrc-api.onrender.com/76600`**
> > > > 
> > > > 
> > > > That's what I'm talking about. the community united against piracy monetization.
> > > > we have this one too. that seems to be working just fine. he only extracts the source. So u need to use it along with consumet.
> > > > https://github.com/cool-dev-guy/rabbitthunder
> > > > This is the related conversation on consumet disc: https://discord.com/channels/987492554486452315/1219195838190977025/1219195838190977025
> > > > I haven't used this yet. but who is using says that is working just fine.
> > > 
> > > 
> > > [dhelbegor](https://github.com/dhelbegor) There are plenty of open-source scrapers available, based on Python, JavaScript, Go, Rust, etc. We don't need to pay for pirated content.
> > 
> > 
> > Do you think you're doing the right thing? You must understand that your actions damage the provider. people who use your code take advantage of it to make money for themselves, which is why the providers have to find a way to stop it.
> 
> [stillmanpeeer](https://github.com/stillmanpeeer) How ironic! So you are from the providers? Don't you use a scraper for your application? We host the API/Application on our VPS. We will pay for our VPS, not for your cheap API.

cheap api? the fucking thing costs 160$/month like what the fuck and thats per person man ha

**Comment by Dragon-Batch** [comment]
@stillmanpeeer advertise your gay shit somewhere else other than open-source repositories you jackass

**Comment by drblgn** [comment]
yo i think i figured out how to extract the sources. how should i share this information ?

**Comment by fsmdeveloper** [comment]
> yo i think i figured out how to extract the sources. how should i share this information ?

share it here. or create a public repo with your code

**Comment by drblgn** [comment]
> > yo i think i figured out how to extract the sources. how should i share this information ?
> 
> share it here. or create a public repo with your code

ok done. if anyone has any questions feel free to ask.

**Comment by fsmdeveloper** [comment]
ok share it

**Comment by drblgn** [comment]
> ok share it

oh, sorry forgot to link it: https://github.com/drblgn/rabbit_wasm

**Comment by fsmdeveloper** [comment]
thank you bro, I'll check it! 😍❤️

**Comment by ClayArsenio26** [comment]
> thank you bro, I'll check it! 😍❤️

its worked bro?

**Comment by fsmdeveloper** [comment]
I didn't check yet.

**Comment by ClayArsenio26** [comment]
> I didn't check yet.

please chat me sir

**Comment by ibz096** [comment]
@drblgn I've tested this and did not get any output. I've opened an issue on your repo, with the same comments below:

### Environment
uname -rv output:
```
5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024
```
Node Version:
```
v18.17.1
```

### Output
When running:
`npx ts-node rabbit.ts
`
The program does not return sources or track as per the below output:

```
{
"sources": [],
"tracks": []
}
```

This occurs regardless if the xrax value in main is modified or not

**Comment by ClayArsenio26** [comment]
> @drblgn I've tested this and did not get any output. I've opened an issue on your repo, with the same comments below:
> 
> ### Environment
> uname -rv output:
> 
> ```
> 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024
> ```
> 
> Node Version:
> 
> ```
> v18.17.1
> ```
> 
> ### Output
> When running: `npx ts-node rabbit.ts ` The program does not return sources or track as per the below output:
> 
> ```
> {
> "sources": [],
> "tracks": []
> }
> ```
> 
> This occurs regardless if the xrax value in main is modified or not

hello bro can you modify too merge consumet with rabbitthunder ??
