### ISSUE TITLE
Aniwatch Key

### ISSUE THREAD

**Issue by jaephefd12** [consumet/consumet.ts#471]
### Describe the bug

Trying to make python tool

### Steps to reproduce

Hello thank you for giving these valuable codes
But im trying to make a python based tool to fetch m3u8 i reached at 
“Sources”:{} but it gives encrypted salted string so please would you mind to tell me about how can i get key for it like in which file(aniwatchtv file not in this ts code)    there is key or full logic 

Pllss i wanna really know i tried to check all requests by intercepting requests but unable to find pls help me with it

tell me logic how can i immply in my python script i dont want readymade keys

### Expected behavior

.

### Actual behavior

.

### Additional context

.

**Comment by animemandir** [comment]
The source encrypt issue still persists in consumet too.
