### ISSUE TITLE
Dubbed Episode IDs are invalid

### ISSUE THREAD

**Issue by Dudeofman** [consumet/consumet.ts#48]
### Describe the bug

When entering the Dub=true parameter through Anilist, the response of the Episode ID's becomes invalid when an info request is made.

### Steps to reproduce

1. Assign dub=true to the Anilist get Anime info request.
2. Make the request.
3. Episode IDs of all episodes can be seen to be invalid.

### Expected behavior

Episode IDs should be valid and functional when the Dubbed parameter is set to true.

### Actual behavior

Invalid Episode IDs when Dub=true.

**Comment by riimuru** [comment]
fixed 👍
