### ISSUE TITLE
Flixhq vidcloud extractor not working due to rabbitstream url path change

### ISSUE THREAD

**Issue by ks3rr** [consumet/consumet.ts#480]
### Describe the bug

Flixhq vidcloud extractor not working due to rabbitstream url path change

### Steps to reproduce

call fetch sources on vidcloud extractor for flixhq

### Expected behavior

should return sources

### Actual behavior

"message": "Something went wrong. Please try again later."

### Additional context

The path seem to have changed to fetch sources on rabbitstream, and also some other things related to this.

**Comment by rahuloberai** [comment]
Same Issue

**Comment by stillmanpeeer** [comment]
We provide the service of getting source from rabbitstream.net. If you are interested, you can contact me to try it out.
Fast speed (< 500ms), only from $160/month, guaranteed high stability. Compensate x2 of your purchase amount if you cannot get the source from rabbitstream.net when they change the algorithm.
.
Methods of retrieving via embed url (crawl embed url, puppeteer ..) rabbitstream.net will be blocked in the near future so it is unstable, we have another way to get the source from rabbitstream.net to ensure it cannot be intercepted block
https://fffapifree.cam
