### ISSUE TITLE
May you please add genre selection with sort functionality (anilist)

### ISSUE THREAD

**Issue by Dudeofman** [consumet/consumet.ts#50]
**Is your feature request related to a problem? Please describe.**
Many of my users reported that they enjoy exploring for new anime to watch by having a look through various Genres. Currently,
Consumet does not support a Genre search like that of the gogo Anime API.

**Describe the solution you'd like**
May you please add a Genre selection to the Anilist API call in Consumet. If possible, with a sort capability that would allow Developers to enable users to explore genres through sorting by year and rating.

**Describe alternatives you've considered**
Continuing the use of the Gogo Anime API

**Comment by riimuru** [comment]
I believe this should be added to an advanced anilist search that I intend to implement with all of the filtering staff.

**Comment by riimuru** [comment]
Added genres filtering without any sorting [here](https://docs.consumet.org/#tag/anilist/operation/getAnimeGenres), and an [advanced search](https://docs.consumet.org/#tag/anilist/operation/getAnimeAdvancedSearch) that includes genres, rating sort and other features
