### ISSUE TITLE
sub or dub query in anilist fetch anime details doesn't work as per documentation.

### ISSUE THREAD

**Issue by ahmedalashhab** [consumet/consumet.ts#51]

**Comment by ahmedalashhab** [comment]
### Describe the bug

The sub or dub query in Anilist, Consumet, returns dubbed info if anything besides blank is inserted into the "dub" query.

### Steps to reproduce

1. perform axios request as follows:  
await axios
      .get(`https://consumet-api.herokuapp.com/meta/anilist/info/${animeId}`, {
        params: {
          dub: "aksdh",
        },
      })
      .then(async (response) => {
        const data = response.data;
        console.log(data);

2. look at the console log. 
3. Console log will show a dub anime returned.
4. Sub anime info will only be returned if the dub query is blank.

### Expected behavior

1. Dub info should be returned only when dub query is set to true as per documentation.
2. Sub info should be returned only when dub query is set to false as per documentation.

### Actual behavior

1. Dub info is returned when dub query is anything not blank.
2. Sub info is returned when dub query is set to blank.

### Additional context

_No response_

**Comment by riimuru** [comment]
fixed
