### ISSUE TITLE
Change gogoanime ajax url !

### ISSUE THREAD

**Issue by regisx001** [consumet/consumet.ts#513]
### Source name

Gogoanime

### Source link

https://ajax.gogocdn.net/ajax

### Language

English

### Source type

Anime

### Additional info

Change to this new ajax url instead of the old one . because it's not working anymore !!

**Comment by hase0278** [comment]
Still works fine for me. What seems to be the problem?
You can try this and this works fine:
https://ajax.gogocdn.net/ajax/page-recent-release-ongoing.html?page=1

**Comment by regisx001** [comment]
oh yes , i just explore the source code and i find that the ajaxUrl already changed , but for some issues it didn't for the npm packages , so i build my own package .
