### ISSUE TITLE
ComicK.io Not working

### ISSUE THREAD

**Issue by siam38** [consumet/consumet.ts#518]
### Describe the bug

Yes only search working fatch manga info not working 

### Steps to reproduce

The api gets blocked for fatch manga info

But its ok in search 
![Screenshot_2024-04-13-16-48-07-45_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/consumet/consumet.ts/assets/56826238/a57b2a80-0d62-464d-b081-eca576a4cb9a)

### Expected behavior

It should return all info probably 

### Actual behavior

Bad request err

**Comment by Toasty360** [comment]
It ain't related to consumet. Fyi, you need to pass referer header to it.
