### ISSUE TITLE
Gogoanime provider change base URL and methods

### ISSUE THREAD

**Issue by JCCode288** [consumet/consumet.ts#528]
### Describe the bug

Gogoanime per today just changed the base url and website interface to anitaku.io

### Steps to reproduce

for base url:
1. use gogo anime provider as usual

for website interface: 
2. extends gogo anime and change the base url to "https://anitaku.io"
3. use popular and movies method

### Expected behavior

for base url:
- it goes to gogo url

for website interface:
- popular and movies method can be used

### Actual behavior

for base url:
- it throws error 504 

for website interface:
-  it throws 404

### Additional context

i used extended version of gogo anime because it prones sudden change. i hope you fixed the method and url so others can use it as well

**Comment by xenmods** [comment]
ps: #526 solves it. i think it needs to be published so it can be used in the package

**Comment by JCCode288** [comment]
> ps: #526 solves it. i think it needs to be published so it can be used in the package

Haven't used #master in a while, but i think the new web interface of gogoanime still broke the provider. Correct me tho

**Comment by JCCode288** [comment]
> ps: #526 solves it. i think it needs to be published so it can be used in the package

Also tried to see what's the difference last night. A lot of page differs from previous version. Stream page also needs a lot of work. Popular and movies now gone

**Comment by JCCode288** [comment]
> ps: #526 solves it. i think it needs to be published so it can be used in the package

update: i've used "https://ww5.gogoanimes.fi" as base url. but somehow recent anime it shows is different with ajax.gogocdn, so it results in not found when i going for stream sources.

i think the main problem is the ajax now has different sources for stream, i somehow managed to use "htutps://ww4.gogoanime2.org" as provider to the stream, and "https://ww5.gogoanimes.fi" as base url. but it still far from perfect, i also needs to change the fetch source method to get url from fetch stream server and adding get default stream server as it is using different interface, so sometimes the stream server is empty just to make it work. 

if it is going to be using "https://anitaku.io/", there's a lot to change because the interface is really different
