### ISSUE TITLE
MovieHdWatch and Goku Provides  Return 404 When Request A Episode Sources

### ISSUE THREAD

**Issue by GathsaraH** [consumet/consumet.ts#554]
### Describe the bug

MovieHdWatch and Goku Can't receive Episode Sources

### Steps to reproduce

1. Download the npm package 
2. Import provider's as mentioned in documents 
3. Try get get episode sourse detail

### Expected behavior

Need to return episode source details as mentioned in the document 

### Actual behavior

Instead of episode details it's returning 404

### Additional context

```
@Injectable()
export class TvShowsService {
  private moviesHd: MovieHdWatch;

  constructor() {
    this.moviesHd = new MOVIES.MovieHdWatch();
  }

  async fetchEpisodeSources(sourceNumber: string, sourceLink: string) {
    try {
      return await this.moviesHd.fetchEpisodeSources('1429498', 'tv/watch-lovely-runner-online-107908');
    } catch (e) {
      console.log(e);
      throw e;
    }
  }

```
![CleanShot 2024-06-23 at 17 07 20](https://github.com/consumet/consumet.ts/assets/66924429/3e143533-5078-4630-b0fc-928376f6485d)

**Comment by Anupm0** [comment]
goku.to and flexhq are only returning movie/series information the servers/{episode id } and streaming link fetching is not working maybe it was discontinued
