### ISSUE TITLE
Unable to create a request to the movies because of lack of "Access-Control-Allow-Origin" header

### ISSUE THREAD

**Issue by dwnppoalt** [consumet/consumet.ts#562]
### Describe the bug

Whenever I try to create a request from the movie providers, the error occurs.

### Steps to reproduce

Here is the code I tried

```js
const movies = new MOVIES.FlixHQ()
    var data = movies.search(search.value).then(data => {
        console.log(data);
    })
```

### Expected behavior

Something like the [documentation](https://github.com/consumet/consumet.ts/blob/master/docs/providers/flixhq.md#search) should what've occured

### Actual behavior

I got this issue at the browser's console tab

`Access to XMLHttpRequest at 'https://flixhq.to/search/five-nights-at-freddy?page=1' from origin 'https://motorola-scholarships-past-regime.trycloudflare.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource`

### Additional context

I'm new at JavaScript, TypeScript, and other languages this is involved in. So it might just be me. Either way, how do I fix it? Thank you! :D

**Comment by shamar-morrison** [comment]
Its not just you, I'm having the same issue.

**Comment by dwnppoalt** [comment]
Hello, I tried using the [API](https://github.com/consumet/api.consumet.org) and host it on Vercel, and it now works for me. If you want, I'll give you a link to the API that I deploy.

**Comment by shamar-morrison** [comment]
> Hello, I tried using the [API](https://github.com/consumet/api.consumet.org) and host it on Vercel, and it now works for me. However, due to the fact that I'm using the API for a Discord App, I no longer use it. If you want, I'll give you a link to the API that I deploy, but it might not be up for long.

So I have to host my own version of the API then? Ok, I can do that. 

I was initially using the [typescript library](https://github.com/consumet/consumet.ts) and that's where I was getting the error like yourself.

**Comment by dwnppoalt** [comment]
> > Hello, I tried using the [API](https://github.com/consumet/api.consumet.org) and host it on Vercel, and it now works for me. However, due to the fact that I'm using the API for a Discord App, I no longer use it. If you want, I'll give you a link to the API that I deploy, but it might not be up for long.
> 
> So I have to host my own version of the API then? Ok, I can do that.
> 
> I was initially using the [typescript library](https://github.com/consumet/consumet.ts) and that's where I was getting the error like yourself.

That worked for me. You can use what the [documentation](https://[github.com/consumet/api.consumet.org?tab=readme-ov-file#installation](https://github.com/consumet/api.consumet.org?tab=readme-ov-file#installation)) says.
