### ISSUE TITLE
Anilist Advanced Search sort response not fully functioning.

### ISSUE THREAD

**Issue by ahmedalashhab** [consumet/consumet.ts#64]
### Describe the bug

When a sort request is made, the response is error 500 for certain sort parameters.

### Steps to reproduce

The following sort parameters work:
1. POPULARITY_DESC
2. TRENDING_DESC
3.  UPDATED_DESC
4. START_DATE_DESC

The following sort parameters return error 500 response.
1. START_DATE_ASC
2. END_DATE_DESC
3. END_DATE_ASC
4. RATING_DESC
5. RATING_ASC
6. TITLE_ASC
7.  TITLE_DESC

### Expected behavior

All the parameters listed in the documentation should return code 200 and successfully respond.

### Actual behavior

Certain parameters work and others do not.

**Comment by riimuru** [comment]
@ahmedalashhab I typed the sorting options incorrectly. It was my fault :(. check the options again
