### ISSUE TITLE
Please include total pages response in Advanced Search.

### ISSUE THREAD

**Issue by ahmedalashhab** [consumet/consumet.ts#65]
**Is your feature request related to a problem? Please describe.**
It's currently difficult for me to develop and implement a complete pagination system due to a lack of total pages in the response.

**Describe the solution you'd like**
Please add a total pages number response in the Advanced search response.

**Describe alternatives you've considered**
Not having a complete pagination system.

**Comment by riimuru** [comment]
Added 👍
