### ISSUE TITLE
Please add a filter in advanced search that allows me to select the exact year of which an anime had started and/or ended. Also airing status filter.

### ISSUE THREAD

**Issue by Dudeofman** [consumet/consumet.ts#68]
**Is your feature request related to a problem? Please describe.**
Please add a filter in advanced search that allows me to select the exact year of which an anime had started and/or ended in the anilist response.

**Describe the solution you'd like**
The ability to filter animes by year

**Comment by riimuru** [comment]
@Dudeofman on anilist there is 
![image](https://user-images.githubusercontent.com/57333995/185814619-7bdae4f9-d53c-46bc-9710-12884f01cb26.png)
and also this
![image](https://user-images.githubusercontent.com/57333995/185814630-34b94ffb-8595-42ff-b3f2-6bf8a7a2fe19.png)
which of these are you willing to use?

**Comment by Dudeofman** [comment]
@riimuru If possible, may you please also add Airing status as well?
<img width="226" alt="image" src="https://user-images.githubusercontent.com/110851951/185875655-734a8c66-42ef-46f3-933a-86166378a711.png">

**Comment by riimuru** [comment]
@Dudeofman will do!

**Comment by riimuru** [comment]
@Dudeofman done 👍
