### ISSUE TITLE
No Dubbed on zoro

### ISSUE THREAD

**Issue by Pacifierjr** [consumet/consumet.ts#71]
### Source name

Zoro

### Source link

https://zoro.to

### Language

English

### Source type

Anime

### Additional info

Hi can i ask if only raw/subbed streaming source only have on zoro api?
thanks in advance.

**Comment by riimuru** [comment]
@Pacifierjr I'm currently scraping only subbed zoro anime only, but I can add a dubbed option as well. i will add it as soon as i have time.

**Comment by Pacifierjr** [comment]
> @Pacifierjr I'm currently scraping only subbed zoro anime only, but I can add a dubbed option as well. i will add it as soon as i have time.

thank you so much hehe

**Comment by Pacifierjr** [comment]
by the way brother, if its okay. if you not busy. can i request to add on zoro route info? like this following details hehe
-Japanese: 
-Synonyms: 
-Aired: 
-Premiered: 
-Duration: 
-Status: 
-MAL Score: 
-Genres:
-Studios: 
-Producers:

so it's more better if someone want to use your zoro api hehe if its okay only.
also id like to use your api for making a php scrapper to stored data to my database but still missing that following so that's why im suggesting hehe.

thanks in advance bro.

**Comment by riimuru** [comment]
@Pacifierjr i won't add that information to zoro alone because i have to make an extra request. Instead of using zoro provider, use the anilist meta provider with zoro. Its basically mapping anilist to zoro to get more information. check the docs here to see how it works: https://github.com/consumet/consumet.ts/docs/providers/anilist.md

**Comment by Pacifierjr** [comment]
> mapping

i see. can i ask if how can use anilist on zoro? because as i see. the anime id of anilist is different on zoro

example on zoro : https://consumet-api.herokuapp.com/anime/zoro/info?id=**one-piece-100**
and on anilist : https://consumet-api.herokuapp.com/meta/anilist/info/**21**

**Comment by riimuru** [comment]
@Pacifierjr it will use anilist ids but the episodes will be for zoro. 
You can get zoro stuff by adding `&provider=zoro` to the url

**Comment by Pacifierjr** [comment]
> &provider=zoro

do you mean like this 
https://docs.consumet.org/#tag/anilist/operation/getAnimeInfo
https://consumet-api.herokuapp.com/meta/anilist/watch/one-piece-episode-1030&provider=zoro (but still gogoanime result)

**Comment by 5H4D0WILA** [comment]
you are using incorrect episode ids

as an example:
https://consumet-api.herokuapp.com/meta/anilist/info/98659?provider=zoro
this returns the same data, but the episode IDs will be for zoro

so then just use
https://consumet-api.herokuapp.com/anime/zoro/watch?episodeId=classroom-of-the-elite-713$episode$12876
for getting the links

**Comment by Pacifierjr** [comment]
> you are using incorrect episode ids
> 
> as an example: https://consumet-api.herokuapp.com/meta/anilist/info/98659?provider=zoro this returns the same data, but the episode IDs will be for zoro
> 
> so then just use https://consumet-api.herokuapp.com/anime/zoro/watch?episodeId=classroom-of-the-elite-713$episode$12876 for getting the links

oh i try this method before but its not work. because its "&" not "?" hehe

**Comment by 5H4D0WILA** [comment]
& is used when you have multiple parameters are added
but the first parameter will always use '?', even if its the only parameter
i would advise you to join the discord server btw, that way i can help you a lot quicker

**Comment by Pacifierjr** [comment]
> & is used when you have multiple parameters are added but the first parameter will always use '?', even if its the only parameter i would advise you to join the discord server btw, that way i can help you a lot quicker

sure brother. thanks a lot.

**Comment by Pacifierjr** [comment]
> @Pacifierjr I'm currently scraping only subbed zoro anime only, but I can add a dubbed option as well. i will add it as soon as i have time.

its work well on my test site : https://ph-c.me/anime/21
but its good if have episode too for dub version hehe

**Comment by riimuru** [comment]
@Pacifierjr dw i will add dub really soon,
